version: "3.7"

services:
  backend:
    image: jerbob92/hoppscotch-backend:latest
    restart: always
    ports:
      - "8989:8989"
    depends_on:
      - mysql
    volumes:
      # Copy config.example.yaml to ./tmp/config.yaml and change the values
      - ./tmp/config.yaml:/etc/api-config/config.yaml
      # Download Firebase admin sdk service account and save it as ./tmp/firebase-admin-sdk.json
      - ./tmp/firebase-admin-sdk.json:/etc/api-config/firebase-admin-sdk.json
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE:-hoppscotch}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:${DB_PORT:-3306}"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
